# Generated by Django 4.2.30 on 2026-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballevent',
            name='pre_state',
            field=models.JSONField(default=dict),
        ),
    ]
